### ISSUE TITLE
fatal error: 'festival.h' file not found

### ISSUE THREAD

**Issue by j-j-kam** [techiaith/pyfestival#12]
Hi, I'm trying to install **festival** on my Mac, but this happens: 

macosx-10.9-x86_64-3.9/_festival.o
    _festival.cpp:2:10: fatal error: 'festival.h' file not found
    #include <festival.h>
             ^~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------

Yes, I have read the **readme** and added the lines you've said. 

<img width="422" alt="Снимок экрана 2021-04-29 в 12 05 48" src="https://user-images.githubusercontent.com/70814983/116527341-3e3a9000-a8e3-11eb-81e9-bc76c41abd94.png">

Please, help to resolve the issue! 
You have only provided a command for Debian for installing the headers. Is there a similar one for MacOS?

**Comment by m-roberts** [comment]
This repository appears to provide a way to install Festival on Mac: https://github.com/pettarin/setup-festival-mbrola
I suspect it will give you the source code which includes the header files that you'll need to refer to for a build.

**Comment by pjrobertson** [comment]
Yes, you need to install festival first on your Mac. The link above form m-roberts appears to work, or there is this gist:

https://gist.github.com/laic/519deca91d50b1ed19307d0c80cb788e
