### ISSUE TITLE
Import error with Python 3.10

### ISSUE THREAD

**Issue by cricalix** [techiaith/pyfestival#14]
Installed with `pip install pyfestival`
Wrote very simple script
```
import festival

festival.sayText("hello world")
```
Expected
==
Festival to say "hello world"

Actual
==
```
>>> import festival
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhill/venvs/tpc/lib/python3.10/site-packages/festival.py", line 3, in <module>
    from . import _festival
ImportError: attempted relative import with no known parent package
>>> 
```

Catching ImportError at the top of festival.py resolves this issue and speech works.

**Comment by cricalix** [comment]
I see the codebase here already has the fix, but PyPI doesn't have it. I also see the other issue about updating PyPI. Will that happen any time soon?

**Comment by pjrobertson** [comment]
Please see version 0.6 on pypi here: https://pypi.org/project/pyfestival/0.6/

Thanks, diolch!

**Comment by cricalix** [comment]
Thank you :)
