### ISSUE TITLE
import festival causes error when script is executed

### ISSUE THREAD

**Issue by ghost** [techiaith/pyfestival#8]
festival works perfectly as a standalone. When I create a python script with the 
following code I get the same error on all commands.

<code>
import festival

festival.info() 
# ImportError: /home/pi/pyfestival/_festival.so: undefined symbol: tgetnum

#OR

festival.textToWav("i like it like that")
# ImportError: /home/pi/pyfestival/_festival.so: undefined symbol: tgetnum
</code>

This is being executed on a raspberry pi 3 B running Raspbian Stretch.
I have spent days on this but nothing I can find on the web seems to help.
From what I found tgetnum has something to do with the ncurses library, which
is install on the machine. However, it is not required by festival for my architecture.
This may not help speed up processing but I would like to see for myself.

**Comment by pjrobertson** [comment]
You could perhaps look at this recent pull request to fix a similar issue on macOS:

https://github.com/techiaith/pyfestival/pull/7/commits/86cab7552bf108656585191cbfd36c57e137ee07

You could try linking to ncurses on your pi then re-building and checking if it works

**Comment by alex-eri** [comment]
It is `speech-tools` bug, i think.

**Comment by mak3rm1k3** [comment]
Anyone make a fix for this? I'm running raspbian and having the same issue.

**Comment by duwudi** [comment]
@mak3rm1k3 [this branch](https://github.com/techiaith/pyfestival/pull/9) fixes all issues I had with Raspberry Pi usage
